{
    'name' : 'Hospital Management',
    'version' : '1.0.0',
    'summary': 'Hospital Management System',
    'author': 'Félicité TEGHOMO',
    'sequence': -100,
    'description': """Hospital Management System""",
    'category': 'Hospital',
    'depends' : ['mail','product'],
    'data': [
        'security/ir.model.access.csv',
        'data/patient_tag_data.xml',
        'wizard/cancel_appointment.xml',
        'views/patient.xml',
        'views/female_patient.xml',
        'views/appointment.xml',
        'views/patient_tag.xml',
        'views/menu.xml',

    ],
    'demo': [],
    'installable': True,
    'application': True,
    'auto_install': False,
    'assets': {},
    'license': 'LGPL-3',
}
